version: '3.8'
services:
  app:
    build: .
    ports:
      - 8083:8083
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dvfabricio_bank
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
    networks:
      - apibank_backend
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: dvfabricio_bank
    networks:
      - apibank_backend
networks:
  apibank_backend:
